### ISSUE TITLE
Add filter support

### ISSUE THREAD

**Issue by glyn** [glyn/go-yamlpath#1]
The best description of JSON path filters I've found is [here](https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html).

**Comment by glyn** [comment]
The following YAML from knative eventing requires filters to find the image environment values:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventing-controller
  namespace: knative-eventing
  labels:
    eventing.knative.dev/release: "v0.13.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventing-controller
  template:
    metadata:
      labels:
        app: eventing-controller
        eventing.knative.dev/release: "v0.13.0"
    spec:
      serviceAccountName: eventing-controller
      containers:
      - name: eventing-controller
        terminationMessagePolicy: FallbackToLogsOnError
        image: gcr.io/knative-releases/knative.dev/eventing/cmd/controller@sha256:5ca5ab7bb3eaa586f7a84fbffbca137f1afa947f89ae7fa42f31fa390aa04168
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: knative.dev/eventing
        - # Legacy CronJobSource
          name: CRONJOB_RA_IMAGE
          value: gcr.io/knative-releases/knative.dev/eventing/cmd/cronjob_receive_adapter@sha256:19ce74c524c8f473559c64849d3db0809c686ff4d6d9e446ebee8f89376e05ed
        - # PingSource
          name: PING_IMAGE
          value: gcr.io/knative-releases/knative.dev/eventing/cmd/ping@sha256:804f5967535b3695763001ff2c26984b2680c6a23364ab406dc79a74609f185b
        - # APIServerSource
          name: APISERVER_RA_IMAGE
          value: gcr.io/knative-releases/knative.dev/eventing/cmd/apiserver_receive_adapter@sha256:d6a5ecd976ba4482aa5e1c9817aaddbeb289d3b9c9d63532f2f27ea982353a42
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - name: metrics
          containerPort: 9090
        - name: profiling
          containerPort: 8008

```
This JSON path expression finds all three images: 
```
$..spec.containers[*].env[?(@.name=='CRONJOB_RA_IMAGE' || @.name=='PING_IMAGE' || @.name=='APISERVER_RA_IMAGE')].value
```
