### ISSUE TITLE
Wildcarded child captures too much

### ISSUE THREAD

**Issue by glyn** [glyn/go-yamlpath#14]
`.*` should capture all the immediate children instead of which it seems to capture the current node as well.

For example, using the web app and the document:
```
store:
  book:
  - category: reference
    author: Nigel Rees
    title: Sayings of the Century
    price: 8.95
  bicycle:
    color: red
    price: 19.95
  feather duster:
    price: 9.95
```
the path `store.*` evaluates to:
```
book
---
- category: reference
  author: Nigel Rees
  title: Sayings of the Century
  price: 8.95
---
bicycle
---
color: red
price: 19.95
---
feather duster
---
price: 9.95
```

It should evaluate to:
```
- category: reference
  author: Nigel Rees
  title: Sayings of the Century
  price: 8.95
---
color: red
price: 19.95
---
price: 9.95
```
